stages:
  - build
  - test

<<<<<<< HEAD
variables:
  PYTHONPATH: "$CI_PROJECT_DIR"
=======
before_script:
  - python3 -m venv venv 
  - source venv/bin/activate 
  - pip install --upgrade pip
  - pip install -r requirements.txt  
  - playwright install 
>>>>>>> 0e9fa56 (Trigger pipeline with shell executor)

build-job:
  stage: build
  script:
    - echo "Build stage completed."

lint-job:
  stage: test
  script:
    - flake8 .

test-job:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.51.0-noble
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]

  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - playwright install --with-deps
  script:
    - pytest -v -s tests/ --test-browser=$BROWSER --headless=True --html=Reports/report.html
  artifacts:
    paths:
      - Reports/report.html
    when: always
    expire_in: 1 week

