stages:
  - build
  - test



build-job:
  stage: build
  script:
    - echo "Build stage completed."

variables:
  PYTHONPATH: "$CI_PROJECT_DIR"

test-job:
  stage: test
  image:python:3.13-slim
  before_script:
  - python3 -m venv venv 
  - source venv/bin/activate 
  - pip install -r requirements.txt  
  - playwright install 

  script:
    - source venv/bin/activate  
    - pytest -v -s tests/ --html=Reports/report.html 
  artifacts:
    paths:
      - Reports/
    when: always
    expire_in: 1 week
  tags:
    - agoda
