stages:
  - build
  - test

variables:
  PYTHONPATH: "$CI_PROJECT_DIR"

build-job:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt --target dependencies/  
    - playwright install --with-deps 
  artifacts:
    paths:
      - dependencies/  
      - /root/.cache/ms-playwright/  
    expire_in: 1 week  

lint-job:
  stage: test
  dependencies:
    - build-job  
  script:
    - pip install --no-index --find-links=dependencies/ -r requirements.txt
    - flake8 .

test-job:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.51.0-noble
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]
  dependencies:
    - build-job
  script:
    - pip install --no-index --find-links=dependencies/ -r requirements.txt  
    - pytest -v -s tests/ --test-browser=$BROWSER --html=Reports/report_$BROWSER.html
  artifacts:
    paths:
      - Reports/
    when: always
    expire_in: 1 week
