stages:
  - build
  - test

image: mcr.microsoft.com/playwright/python:v1.51.0-noble

variables:
  PYTHONPATH: "$CI_PROJECT_DIR/venv/lib/python3.10/site-packages"

build-job:
  stage: build
  script:
    - apt update && apt install -y python3.10-venv
    - python -m venv venv  # Create virtual environment
    - source venv/bin/activate  # Activate venv
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - playwright install --with-deps  # Install browsers in venv
  artifacts:
    paths:
      - venv/  # Save the virtual environment
    expire_in: 1 week

lint-job:
  stage: test
  script:
    - source venv/bin/activate  # Activate venv
    - flake8 .

test-job:
  stage: test
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]

  script:
    - source venv/bin/activate  # Activate venv
    - pytest -v -s tests/ --browser $BROWSER --html=Reports/report_$BROWSER.html
  artifacts:
    paths:
      - Reports/
    when: always
    expire_in: 1 week
