image: python:3.13.2-slim 

stages:
  - build
  - test

before_script:
  - python3 -m venv venv 
  - source venv/bin/activate 
  - pip install --upgrade pip
  - pip install -r requirements.txt  
  - playwright install 

build:
  stage: build
  script:
    - echo "Build stage completed."

test-playwright:
  stage: test
  script:
    - source venv/bin/activate  
    - pytest -v -s --html=Reports/report.html
  artifacts:
    paths:
      - Reports/report.html  
      - Reports/Images/
