stages:
  - build
  - test

image: python:3.12

variables:
  PYTHONPATH: "$CI_PROJECT_DIR/venv/lib/python3.12/site-packages"

build-job:
  stage: build
  script:
    - python3 -m venv venv  
    - source venv/bin/activate  
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - playwright install --with-deps  
  artifacts:
    paths:
      - venv/ 
    expire_in: 1 week

lint-job:
  stage: test
  script:
    - source venv/bin/activate  
    - flake8 .

test-job:
  stage: test
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]

  script:
    - source venv/bin/activate  
    - pytest -v -s tests/ --browser $BROWSER --html=Reports/report_$BROWSER.html
  artifacts:
    paths:
      - Reports/
    when: always
    expire_in: 1 week
