stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Build stage completed."

lint-job:
  stage: test
  script:
<<<<<<< HEAD
    - flake8 .

test-job:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.51.0-noble
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]

  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - playwright install --with-deps
  script:
    - pytest -v -s tests/ --test-browser=$BROWSER --headless=True --html=Reports/report.html
  artifacts:
    paths:
      - Reports/report.html
    when: always
    expire_in: 1 week
=======
    - source venv/bin/activate  
    - pytest -v -s tests/ --html=Reports/report.html 
  artifacts:
    paths:
      - /Reports
      when: always
      expire_in: 1 week
>>>>>>> 49433a2 (fixing artifact issues)
