stages:
  - test

variables:
  PYTHONPATH: "$CI_PROJECT_DIR"


before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - playwright install --with-deps
    - apt-get update && apt-get install -y nodejs npm
    - npm install

cache:
  paths:
    - node_modules/

test:
  stage: test
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]
  script:
    - npm run test:all-browsers
  artifacts:
    paths:
      - Reports/report_$BROWSER.html
    when: always
    expire_in: 1 week
