image: mcr.microsoft.com/playwright/python:v1.50.0-noble 

stages:
  - install
  - test


before_script:
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - playwright install --with-deps

test:
  stage: test
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]
  script:
    - pytest -v -s tests/ --browser=$BROWSER --html=Reports/report_$BROWSER.html
  artifacts:
    paths:
      - Reports/report_$BROWSER.html
    when: on_failure
    expire_in: 1 week
