stages:
  - build
  - test

variables:
  PYTHONPATH: "$CI_PROJECT_DIR"

build-job:
  stage: build
  script:
    - echo "Build stage completed."

test-job:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.51.0-noble

  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - playwright install --with-deps
  script:
    - source venv/bin/activate
    - pytest -v -s tests/ --html=Reports/report.html
  artifacts:
    paths:
      - Reports/
    when: always
    expire_in: 1 week

