image: python:3.13.2-slim 

stages:
  - build
  - test

before_script:
  - python3 -m venv venv 
  - source venv/bin/activate 
  - pip install -r requirements.txt  
  - playwright install 

build-job:
  stage: build
  script:
    - echo "Build stage completed."

test-job:
  stage: test
  script:
    - source venv/bin/activate  
    - pytest -v -s tests/ --html=$CI_PROJECT_DIR/artifacts
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week
