image: mcr.microsoft.com/playwright/python:v1.41.0-focal  # Prebuilt Playwright image

stages:
  - install
  - lint
  - test

install-job:
  stage: install
  script:
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - playwright install --with-deps
  artifacts:
    paths:
      - .cache/pip  # ✅ Save installed packages
      - .cache/ms-playwright  # ✅ Save downloaded Playwright browsers
    expire_in: 1 week

lint-job:
  stage: lint
  needs:
    - install-job
  script:
    - flake8 .

test-job:
  stage: test
  needs:
    - install-job
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]
  script:
    - pytest -v -s tests/ --browser $BROWSER --html=Reports/report_$BROWSER.html
  artifacts:
    paths:
      - Reports/report_$BROWSER.html
    when: on_failure
    expire_in: 1 week
