image: mcr.microsoft.com/playwright/python:v1.50.0-noble 

stages:
  - install
  - test

variables:
  PYTHONPATH: "$CI_PROJECT_DIR"


before_script:
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - playwright install --with-deps
    - npm install

test:
  stage: test
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]
  script:
    - npm run test:all-browsers
  artifacts:
    paths:
      - Reports/report_$BROWSER.html
    when: always
    expire_in: 1 week
